from sizeA import tree


T=tree()
T.insert(91,"")
print("Dopo aver inserito  91 --> size=",T.size)
T.insert(77,"L")
print("Dopo aver inserito  77 --> size=",T.size)
T.insert(33,"LL")
print("Dopo aver inserito  33 --> size=",T.size)
T.insert(333,"LL")
print("Dopo aver inserito 333 --> size=",T.size)
T.insert(54,"LLR")
print("Dopo aver inserito  54 --> size=",T.size)
T.insert(9,"LR")
print("Dopo aver inserito   9 --> size=",T.size)
T.insert(6,"R")
print("Dopo aver inserito   6 --> size=",T.size)
T.insert(1,"RL")
print("Dopo aver inserito   1 --> size=",T.size)
T.insert(5,"RR")
print("Dopo aver inserito   5 --> size=",T.size)
T.insert(57,"LLR")
print("Dopo aver inserito  57 --> size=",T.size)

print()
print("Inorder")
T.inorder()
