from pari import tree


T=tree()
print("Albero vuoto")
print("Pari=",T.pari)
print("Inserisco 91")
T.insert(91,"")
print("Pari=",T.pari)
print("Inserisco 77")
T.insert(77,"L")
print("Pari=",T.pari)
print("Inserisco 33")
T.insert(33,"LL")
print("Pari=",T.pari)
print("Inserisco 34 al posto di 33")
T.insert(34,"LL")
print("Pari=",T.pari)
print("Inserisco 54")
T.insert(54,"LLR")
print("Pari=",T.pari)
print("Inserisco 9")
T.insert(9,"LR")
print("Pari=",T.pari)
print("Inserisco 6")
T.insert(6,"R")
print("Pari=",T.pari)
print("Inserisco 1")
T.insert(1,"RL")
print("Pari=",T.pari)
print("Inserisco 5")
T.insert(5,"RR")
print("Pari=",T.pari)
print("Inserisco 57")
T.insert(57,"RRL")
print("Pari=",T.pari)
print("Inserisco 53 al posto di 54")
T.insert(53,"LLR")
print("Pari=",T.pari)

print()
print("Inorder")
T.inorder()
