#!/bin/csh

make

set KEYDIR="KEYS/"
set CTDIR="CT-SIG/"
set RSAPrivateKey="RSAPrivate.pem"
set RSAPublicKey="RSAPublic.pem"
set DSAPrivateKey="DSAPrivate.pem"
set DSAPublicKey="DSAPublic.pem"
set ct="Ciphertext.txt"
set sig="Signature.txt"

echo "Generating RSA key pair using ex01RSA"
echo "Results stored in files: "
echo "  Public key in file:              " ${KEYDIR}${RSAPublicKey}
echo "  Encrypted Private key in file:   " ${KEYDIR}${RSAPrivateKey}
echo "  UnEncrypted Private key in file: " ${KEYDIR}"Un"${RSAPrivateKey}
echo "     in PKCS#8 encoded in PEM"
./ex01RSA ${KEYDIR}${RSAPublicKey} ${KEYDIR}${RSAPrivateKey} ${KEYDIR}"Un"${RSAPrivateKey}
echo
echo

echo "Generating DSA key pair using ex01DSA"
echo "Results stored in files: "
echo "  Public key in file:              " ${KEYDIR}${DSAPublicKey}
echo "  Encrypted Private key in file:   " ${KEYDIR}${DSAPrivateKey}
echo "  UnEncrypted Private key in file: " ${KEYDIR}"Un"${DSAPrivateKey}
echo "     in PKCS#8 encoded in PEM"
./ex01DSA ${KEYDIR}${DSAPublicKey} ${KEYDIR}${DSAPrivateKey} ${KEYDIR}"Un"${DSAPrivateKey}


echo "Printing the RSA key pair using ex02"
./ex02 ${KEYDIR}${RSAPublicKey} ${KEYDIR}${RSAPrivateKey} 
echo
 
echo "Printing the DSA key pair using ex02"
./ex02 ${KEYDIR}${DSAPublicKey} ${KEYDIR}${DSAPrivateKey} 
echo

echo "Encrypting and decrypting message using ex03RSA"
./ex03RSA ${KEYDIR}${RSAPublicKey} ${KEYDIR}${RSAPrivateKey} 
echo

echo "Encrypting message using the EVP interface"
./ex04Enc ${KEYDIR}${RSAPublicKey} ${CTDIR}${ct}
echo "Decrypting message using the EVP interface"
./ex05Dec ${KEYDIR}${RSAPrivateKey} ${CTDIR}${ct}
echo

echo "Signing message using RSA Key"
./ex06Sig ${KEYDIR}${RSAPrivateKey} ${CTDIR}"RSA"${sig}
echo "Verifying message using RSA Key"
./ex07Ver ${KEYDIR}${RSAPublicKey} ${CTDIR}"RSA"${sig}
echo


echo "Signing message using DSA Key"
./ex06Sig ${KEYDIR}${DSAPrivateKey} ${CTDIR}"DSA"${sig}
echo "Verifying message using DSA Key"
./ex07Ver ${KEYDIR}${DSAPublicKey} ${CTDIR}"DSA"${sig}
echo

